#!/bin/sh

export HOME="/root"
export SHELL="/bin/bash"
export XDG_SESSION_TYPE="wayland"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_RUNTIME_DIR="/run/user/0"
export NO_AT_BRIDGE=1
export LANG=en_US.UTF-8
export PATH="/bin:/usr/bin:/usr/sbin:/sbin:/bin:/usr/local/bin:/usr/local/sbin"
export XCURSOR_THEME="Adwaita"
export XCURSOR_SIZE="24"
export XCURSOR_PATH="/usr/share/icons:/usr/share/pixmaps"
export SDL_VIDEODRIVER=wayland
export SDL_AUDIODRIVER=pipewire
export LIBGL_ALWAYS_SOFTWARE=1
export WLR_RENDERER_ALLOW_SOFTWARE=1
export WLR_RENDERER=pixman

mkdir -p /tmp/.X11-unix
mkdir -p /tmp/.ICE-unix
mkdir -p $HOME/.config/dconf
mkdir -p /run/dbus
mkdir -p /var/lib/dbus
mkdir -p $XDG_RUNTIME_DIR

chmod 01777 /tmp/.X11-unix
chmod 0777 /tmp/.ICE-unix
chmod 0700 $XDG_RUNTIME_DIR

dbus-daemon --system --fork
dbus-uuidgen --ensure

udevd --daemon

while [ ! -e "/run/udev/control" ]; do
    sleep 0.5
done

udevadm settle

exec dbus-run-session -- seatd-launch -- startxfce4 --wayland
