#!/bin/sh

/bin/mkdir -p /dev/
/bin/mount -t devtmpfs devtmpfs /dev

/bin/echo "Aether-OS init script is running..."

/bin/mkdir -p /mnt/

root_mounted=0

for path in /dev/*; do
    if [[ $path == *"part"* ]]; then
        /bin/echo "Trying mount $path as root"
        /bin/mount -t ext $path /mnt/
        if [ $? -eq 0 ]; then
            root_mounted=1
            break
        fi
    fi
done

/bin/umount /dev

if [ $root_mounted -eq 0 ]; then
    /bin/echo "Mount root failed..."
    exec /bin/sh
fi

/bin/mkdir -p /proc/

/bin/mount -t proc proc /proc

init_path=$(sed -n 's/.*init=\([^ ]*\).*/\1/p' /proc/cmdline)

/bin/umount /proc

/bin/mkdir -p /mnt/dev/
/bin/mkdir -p /mnt/proc/
/bin/mkdir -p /mnt/sys/
/bin/mkdir -p /mnt/run/
/bin/mkdir -p /mnt/tmp/

/bin/mount -t devtmpfs /mnt/dev
/bin/mkdir -p /mnt/dev/shm
/bin/mount -t tmpfs tmpfs /mnt/dev/shm
/bin/mkdir -p /mnt/dev/pts
/bin/mount -t devpts devpts /mnt/dev/pts
/bin/mount -t proc proc /mnt/proc
/bin/mount -t sysfs sysfs /mnt/sys
/bin/mount -t tmpfs tmpfs /mnt/run
/bin/mount -t tmpfs tmpfs /mnt/tmp

/bin/echo "Ready to switch root..."

# export LIBGL_ALWAYS_SOFTWARE=1
# export WLR_RENDERER_ALLOW_SOFTWARE=1
# export WLR_RENDERER=pixman
exec /sbin/switch_root /mnt/ ${init_path:-/sbin/init}
