#!/bin/sh

/bin/mkdir -p /dev/
/bin/mount -t devtmpfs devtmpfs /dev

/bin/echo "Aether-OS init script is running..."

/bin/mkdir -p /mnt/

root_mounted=0

for path in /dev/*; do
    if [[ $path == *"part"* ]]; then
        /bin/echo "Trying mount $path as root"
        /bin/mount -t ext $path /mnt/
        if [ $? -eq 0 ]; then
            root_mounted=1
            break
        fi
    fi
done

if [ $root_mounted -eq 0 ]; then
    /bin/echo "Mount root failed..."
    exec /bin/sh
fi

/bin/mkdir -p /proc/
/bin/mkdir -p /sys/
/bin/mkdir -p /run/
/bin/mkdir -p /tmp/

/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys
/bin/mount -t tmpfs tmpfs /run
/bin/mount -t tmpfs tmpfs /tmp

init_path=$(sed -n 's/.*init=\([^ ]*\).*/\1/p' /proc/cmdline)

/bin/mkdir -p /mnt/dev/
/bin/mkdir -p /mnt/proc/
/bin/mkdir -p /mnt/sys/
/bin/mkdir -p /mnt/run/
/bin/mkdir -p /mnt/tmp/

/bin/mount --move /dev /mnt/dev
/bin/mount -t tmpfs tmpfs /mnt/dev/shm
/bin/mount --move /proc /mnt/proc
/bin/mount --move /sys /mnt/sys
/bin/mount --move /run /mnt/run
/bin/mount --move /tmp /mnt/tmp

/bin/echo "Ready to switch root..."

exec /sbin/switch_root /mnt/ ${init_path:-/sbin/init}

