timeout: 0

/NeoAether-OS
    protocol: limine

    path: boot():/kernel
    resolution: 1440x900x32
    kernel_cmdline: console=tty0 init=/usr/lib/aether/init

    module_path: boot():/initramfs.img
